services:
  postgres:
    image: postgres:18.4
    container_name: cluster-db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data_18:/var/lib/postgresql

  redis:
    image: redis:8.10
    container_name: cluster-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data_8:/data

volumes:
  pg_data_18:
  redis_data_8: