import type { Metadata } from "next";
import "./globals.css";
import GoogleProvider from "@/app/context/GoogleProvider";
import { Outfit } from 'next/font/google';

// Configure the font
const outfit = Outfit({ 
  subsets: ['latin'],
  variable: '--font-sans', // This matches your Tailwind config!
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${outfit.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <GoogleProvider>
          {children}
        </GoogleProvider>
      </body>
    </html>
  );
}
