#!/usr/bin/env bash
# Installs this project's git hooks. Safe to re-run: it overwrites the installed
# hooks with the latest version.
#
# Usage: bash scripts/install-hooks.sh

set -euo pipefail

THIS_DIR=$(dirname "$0")
ROOT_DIR="$THIS_DIR/.."

cd "$ROOT_DIR"

HOOKS_DIR=$(git rev-parse --git-path hooks)
mkdir -p "$HOOKS_DIR"

echo "Installing pre-commit hook into $HOOKS_DIR..."

# Quoted delimiter: the hook body is written verbatim, without variable expansion
cat > "$HOOKS_DIR/pre-commit" <<'EOF'
#!/usr/bin/env bash
# Pre-commit hook: lint + format staged files with Biome.
# Generated by scripts/install-hooks.sh — edit that file, not this one.

set -euo pipefail

staged_files=$(git diff --cached --name-only --diff-filter=ACMR)
[ -z "$staged_files" ] && exit 0

# Files that also have unstaged changes; re-staging them would commit those changes too
partially_staged=$(comm -12 <(echo "$staged_files" | sort) <(git diff --name-only | sort))

unstaged_diff() {
  [ -z "$partially_staged" ] && return 0
  echo "$partially_staged" | xargs -d '\n' git diff --
}
partial_before=$(unstaged_diff)

echo "pre-commit: running Biome on staged files..."

# Apply safe fixes, formatting and import sorting; fail on remaining errors
if ! npx --no-install biome check --write --staged --no-errors-on-unmatched --files-ignore-unknown=true; then
  echo ""
  echo "pre-commit: Biome found problems it couldn't fix. Fix them and commit again."
  exit 1
fi

# Re-stage fully staged files so the fixes are part of this commit
fully_staged=$(comm -23 <(echo "$staged_files" | sort) <(echo "$partially_staged" | sort))
if [ -n "$fully_staged" ]; then
  echo "$fully_staged" | while IFS= read -r file; do
    if [ -f "$file" ]; then git add -- "$file"; fi
  done
fi

if [ -n "$partially_staged" ] && [ "$(unstaged_diff)" != "$partial_before" ]; then
  echo ""
  echo "pre-commit: Biome changed these partially staged files, but the fixes were NOT staged:"
  echo "$partially_staged" | sed 's/^/  - /'
  echo "Review the changes, stage them, and commit again."
  exit 1
fi
EOF

chmod +x "$HOOKS_DIR/pre-commit"

echo "Pre-commit hook installed!"
